name: CI/CD Pipeline for Next.js

on:
  push:
    branches:
      - dev

jobs:
  build-and-test:
    name: Build and Test
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm run test

      - name: Build Project
        run: npm run build

      - name: Deploy to Main Branch
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout main
          git merge dev
          git push origin main
